
name: Demo workflow

# on:
#   workflow_dispatch:
#   push:
#     branches:
#     - main
#     - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**
env:
    MY_VAR: Hi there! This workflow running from
    FNAME: Dev
    MNAME: environment
    managedby: Surendra
  

jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v6.0.1

    - name: Print a greeting
      run: |
       echo $MY_VAR $FNAME $MNAME thanks to $managedby !.
        # run: echo "Hello World,This is my first workflow from GitHub Actions"

    # - name: List files
    #   run: ls -l

    # - name: Read Readme.md
    #   run: cat README.md
     
   
