
name: Demo workflow

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - features/**
  # pull_request:
  #   branches:
  #   - main
  #   - features/**
env:
    MY_VAR: Hi there! My name is
    FIRST_NAME: Mona
    MIDDLE_NAME: The
    LAST_NAME: Octocat
    run: |
      echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

jobs:
  firstjob:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v6.0.1

    - name: Print a greeting
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
        # run: echo "Hello World,This is my first workflow from GitHub Actions"

    - name: List files
      run: ls -l

    - name: Read Readme.md
      run: cat README.md
     
   
